grails-app/domain/ws/RoleLG.groovy
package ws

import groovy.transform.EqualsAndHashCode
import groovy.transform.ToString

@EqualsAndHashCode(includes='authority')
@ToString(includes='authority', includeNames=true, includePackage=false)
class RoleLG implements Serializable {

	private static final long serialVersionUID = 1

	String	nombre
	String	authority = "ROLE_OPERADOR"
	Date	dateCreated
    Date	lastUpdated
    UserLG	id_Autor

	RoleLG(String nombre, String authority) {
		this()
		this.nombre = nombre
		this.authority = authority
	}

	static constraints = {
		authority		(blank: false)
		nombre			(nullable:false)
		dateCreated		(widget:'display')
        lastUpdated		(widget:'display')
        id_Autor		(nullable:true, widget:'display')
	}

	static mapping = {
		sort nombre: "asc"
		table 'ROLELG'
		cache true
		id_Autor column:'id_autor'
	}

	String toString() {
        return nombre
    }
}

grails-app/controllers/ws/RoleLGController.groovy
package ws

import static org.springframework.http.HttpStatus.*
import org.springframework.transaction.TransactionStatus
import grails.transaction.*

@Transactional(readOnly = true)
class RoleLGController {
    //Identificación de la sesion del usuario
    def springSecurityService;
    
    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
		if (!session.getAttribute("controller_active").equals("RoleLG")){
			session.setAttribute("controller_active", "RoleLG");
			session.setAttribute("roleLG_search_rows", 10);
			session.setAttribute("roleLG_search_word", "");
			session.setAttribute("roleLG_search_offset", 0);
		}
		
        //Recuperación de la pagina en que se encuentra
        if (params.offset){
			
        }else if (session.getAttribute("roleLG_search_offset")){
			params.offset = session.getAttribute("roleLG_search_offset");
        } else {
			params.offset = 0;
        }
		//Recuperación de limite maximo de registros visibles
		if (params.search_rows) {
			if (params.search_rows != session.getAttribute("roleLG_search_rows")) params.offset = 0;
			params.max = params.search_rows.toInteger();
        } else if (session.getAttribute("roleLG_search_rows")){
			params.max = session.getAttribute("roleLG_search_rows").toInteger();
        } else {
			params.max = 10;
        }
        params.search_rows = params.max;
        //Recuperando la palabra de busqueda
        if (params.search_clean == "1") {
			params.search_word = "";
			params.offset = 0;
		} else if (params.search_word){
			//Enviada la palabra a buscar
			if (params.search_word != session.getAttribute("roleLG_search_word")) params.offset = 0;
        } else if (session.getAttribute("roleLG_search_word")){
			params.search_word = session.getAttribute("roleLG_search_word");
        }
        
        def itemsList = RoleLG.createCriteria().list (params) {
			/*
            if ( params.search_word ) {
				or {
					ilike("nombre_1", "%${params.search_word}%")
					ilike("nombre_2", "%${params.search_word}%")
				}
            }
            */
            if ( params.search_word ) {
				ilike("nombre", "%${params.search_word}%")
            }
        }
        
        session.setAttribute("roleLG_search_rows", params.search_rows);
        session.setAttribute("roleLG_search_word", params.search_word);
        session.setAttribute("roleLG_search_offset", params.offset);
        
        respond itemsList, model:[roleLGCount: itemsList.totalCount]
    }

    def show(RoleLG roleLG) {
        respond roleLG
    }

    def create() {
        respond new RoleLG(params)
    }

    @Transactional
    def save(RoleLG roleLG) {
        if (roleLG == null) {
            transactionStatus.setRollbackOnly()
            notFound()
            return
        }

        if (roleLG.hasErrors()) {
            transactionStatus.setRollbackOnly()
            respond roleLG.errors, view:'create'
            return
        }
		
		/*
		int id = 0;
        if (RoleLG.createCriteria().get {projections {max "id"}} as Integer != null){
           id = RoleLG.createCriteria().get {projections {max "id"}} as int
        }
        id++
         roleLG.id = id
        */
        
        // Recupera el id del autor
		if (springSecurityService.principal)
			roleLG.id_Autor = UserLG.findById(springSecurityService.principal.id);
		
        roleLG.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'roleLG.label', default: 'RoleLG'), roleLG.id])
                redirect roleLG
            }
            '*' { respond roleLG, [status: CREATED] }
        }
    }

    def edit(RoleLG roleLG) {
        respond roleLG
    }

    @Transactional
    def update(RoleLG roleLG) {
        if (roleLG == null) {
            transactionStatus.setRollbackOnly()
            notFound()
            return
        }

        if (roleLG.hasErrors()) {
            transactionStatus.setRollbackOnly()
            respond roleLG.errors, view:'edit'
            return
        }

        roleLG.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'roleLG.label', default: 'RoleLG'), roleLG.id])
                redirect roleLG
            }
            '*'{ respond roleLG, [status: OK] }
        }
    }

    @Transactional
    def delete(RoleLG roleLG) {

        if (roleLG == null) {
            transactionStatus.setRollbackOnly()
            notFound()
            return
        }

        roleLG.delete flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'roleLG.label', default: 'RoleLG'), roleLG.id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }
    
    @Transactional
    def remove(RoleLG roleLG) {

        if (roleLG == null) {
            transactionStatus.setRollbackOnly()
            notFound()
            return
        }

        roleLG.delete flush:true

		flash.message = message(code: 'default.deleted.message', args: [message(code: 'roleLG.label', default: 'RoleLG'), roleLG.id])
		redirect action:"index", method:"GET"
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'roleLG.label', default: 'RoleLG'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails-app/views/roleLG/create.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'roleLG.label', default: 'RoleLG')}" />
        <g:set var="entitiesName" value="${message(code: 'roleLG.label', default: 'RoleLGs')}" />
        <title><g:message code="default.create.label" args="[entityName]" /></title>
        <style>
            #nombre {width:50%}
        </style>
        <script language="javascript">
			$( document ).ready(function() {
				$("#myTime").show();
			});
			
			function go(id_tag){
				$('[name="footer-'+id_tag+'"]')[0].click();
			}
		</script>
    </head>
    <body>
		<g:render template="/layouts/menu" />
		<!-- .menu-box -->
		<div class="breadcrumb-box">
		  <div class="container">
			<ul class="breadcrumb">
			  <li><a href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
			  <li><g:link action="index"><g:message code="default.list.label" args="[entitiesName]" /></g:link></li>
			  <li class="active"><g:message code="default.new.label" args="[entityName]" /></li>
			</ul>	
		  </div>
		</div>
		<!-- .breadcrumb-box -->
        <a href="#create-roleLG" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav_topbar" role="navigation">
            <ul>
				<li><a href="javascript:go('save')"		class="save"><g:message code="default.button.save.label" default="Edit" /></a></li>
                <li><a href="javascript:go('close')"	class="close"><g:message code="default.button.close.label" default="close" /></a></li>
            </ul>
        </div>
        <div id="create-roleLG" class="content scaffold-create" role="main">
            <g:if test="${flash.message}">
				<script type="text/javascript">
					  $.amaran({
						'theme'     :'awesome ok',
						'delay'     :5000,
						'position'  :'top left',
						'content'   :{
							bgcolor:'#27ae60',
							color:'#fff',
							title:'¡Mensaje!',
							message:'${flash.message}',
							info:'', %{--<g:formatDate format="yyyy-MM-dd HH:mm:ss" date="${new Date()}"/>--}%
							icon:'fa fa-bell-o fa-2x'
						},
						'inEffect': 'slideLeft',
						'outEffect' :'slideLeft'
					});
				</script>
			</g:if>
            <g:hasErrors bean="${this.roleLG}">
				<script type="text/javascript">
					var mensaje = "";
					<g:eachError bean="${this.roleLG}" var="error">
					mensaje += '<g:message error="${error}"/></br>';
					</g:eachError>
					$.amaran({
						'theme'     :'awesome ok',
						'delay'     :5000,
						'position'  :'top left',
						'content'   :{
							bgcolor:'#27ae60',
							color:'#fff',
							title:'¡Mensaje!',
							message:mensaje,
							info:'', %{--<g:formatDate format="yyyy-MM-dd HH:mm:ss" date="${new Date()}"/>--}%
							icon:'fa fa-bell-o fa-2x'
						},
						'inEffect': 'slideLeft',
						'outEffect' :'slideLeft'
					});
				</script>
            </g:hasErrors>
            <g:form action="save">
                <fieldset class="form">
                    
                    <f:all bean="roleLG"/>
                    
                    %{--
                    <f:with bean="roleLG">
                        <f:field property="nombre"/>
                        <f:field property="OTROCAMPO" label="OTRO CAMPO"/>
                    </f:with>
					--}%
                    
                </fieldset>
                <g:submitButton name="footer-save" style="visibility:hidden;position:absolute;top:0px;width:0px;"/>
                <fieldset class="buttons">
					<g:link class="save" url="javascript:go('save')"><g:message code="default.button.save.label" default="Save" /></g:link>
                    <g:link name="footer-close" class="close" action="index"><g:message code="default.button.close.label" default="Close" /></g:link>
                </fieldset>
            </g:form>
        </div>
    </body>
</html>

grails-app/views/roleLG/edit.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'roleLG.label', default: 'RoleLG')}" />
        <g:set var="entitiesName" value="${message(code: 'roleLG.label', default: 'RoleLGs')}" />
        <title><g:message code="default.edit.label" args="[entityName]" /></title>
         <style>
            #nombre {width:50%}
        </style>
        <script language="javascript">
			$( document ).ready(function() {
				$("#myTime").show();
			});
			
			function go(id_tag){
				$('[name="footer-'+id_tag+'"]')[0].click();
			}
		</script>
    </head>
    <body>
		<g:render template="/layouts/menu" />
		<!-- .menu-box -->
		<div class="breadcrumb-box">
		  <div class="container">
			<ul class="breadcrumb">
			  <li><a href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
			  <li><g:link action="index"><g:message code="default.list.label" args="[entitiesName]" /></g:link></li>
			  <li><g:link action="show" resource="${this.roleLG}"><g:message code="default.show.label" args="[entityName]" /></g:link></li>
			  <li class="active"><g:message code="default.edit.label" /> ${roleLG.nombre}</li>
			</ul>	
		  </div>
		</div>
		<!-- .breadcrumb-box -->
        <a href="#edit-roleLG" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav_topbar" role="navigation">
            <ul>
				<li><a href="javascript:go('save')"		class="save"><g:message code="default.button.save.label" default="Edit" /></a></li>
                <li><a href="javascript:go('close')"	class="close"><g:message code="default.button.close.label" default="close" /></a></li>
            </ul>
        </div>
        <div id="edit-roleLG" class="content scaffold-edit" role="main">
			<g:if test="${flash.message}">
				<script type="text/javascript">
					  $.amaran({
						'theme'     :'awesome ok',
						'delay'     :5000,
						'position'  :'top left',
						'content'   :{
							bgcolor:'#27ae60',
							color:'#fff',
							title:'¡Mensaje!',
							message:'${flash.message}',
							info:'', %{--<g:formatDate format="yyyy-MM-dd HH:mm:ss" date="${new Date()}"/>--}%
							icon:'fa fa-bell-o fa-2x'
						},
						'inEffect': 'slideLeft',
						'outEffect' :'slideLeft'
					});
				</script>
			</g:if>
            <g:hasErrors bean="${this.roleLG}">
				<script type="text/javascript">
					var mensaje = "";
					<g:eachError bean="${this.roleLG}" var="error">
					mensaje += '<g:message error="${error}"/></br>';
					</g:eachError>
					$.amaran({
						'theme'     :'awesome ok',
						'delay'     :5000,
						'position'  :'top left',
						'content'   :{
							bgcolor:'#27ae60',
							color:'#fff',
							title:'¡Mensaje!',
							message:mensaje,
							info:'', %{--<g:formatDate format="yyyy-MM-dd HH:mm:ss" date="${new Date()}"/>--}%
							icon:'fa fa-bell-o fa-2x'
						},
						'inEffect': 'slideLeft',
						'outEffect' :'slideLeft'
					});
				</script>
            </g:hasErrors>
            <g:form resource="${this.roleLG}" method="PUT">
                <g:hiddenField name="version" value="${this.roleLG?.version}" />
                <fieldset class="form">
                    
                    <f:all bean="roleLG"/>
                    
                    %{--
					<f:with bean="roleLG">
                        <f:field property="nombre"/>
                        <f:field property="OTROCAMPO" label="OTRO CAMPO"/>
                    </f:with>
					--}%
                    
                </fieldset>
                <g:submitButton name="footer-save" style="visibility:hidden;position:absolute;top:0px;width:0px;"/>
                <fieldset class="buttons">
					<g:link class="save" url="javascript:go('save')"><g:message code="default.button.save.label" default="Save" /></g:link>
                    <g:link name="footer-close" class="close" action="show" resource="${this.roleLG}"><g:message code="default.button.close.label" default="Close" /></g:link>
                </fieldset>
            </g:form>
        </div>
    </body>
</html>

grails-app/views/roleLG/index.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'roleLG.label', default: 'RoleLG')}" />
        <g:set var="entitiesName" value="${message(code: 'roleLG.label', default: 'RoleLGs')}" />
        <title><g:message code="default.list.label" args="[entityName]" /></title>
        <script language="javascript">
			$(document).ready(function(e){
				$("#myTime").show();
				$(".search-panel .dropdown-menu").find("a").click(function(e) {
					e.preventDefault();
					var param_max = $(this).attr("href").replace("#","");
					var concept = $(this).text();
					$(".search-panel span#search_concept").text(concept);
					$("#search_rows").val(param_max);
					if ($("#search_word").val() == ""){
						$("#search_clean").val("1");
					}
					$( "#search_form" ).submit();
				});
				$("#btn-search").click(function(e) {
					if ($("#search_word").val() == ""){
						$("#search_clean").val("1");
					}
					$( "#search_form" ).submit();
				});
				$("#search_word").on("keydown", function (e) {
					if (e.keyCode == 13) {
						if ($("#search_word").val() == ""){
							$("#search_clean").val("1");
						}
						$( "#search_form" ).submit();
					}
				});
				/*
				$("#search_word").donetyping(function(){
					if ($("#search_word").val() == ""){
						$("#search_clean").val("1");
					}
					$( "#search_form" ).submit();
				});
				*/
				$("#search_word").focus();
			});
			
			function jconfirm(pregunta,mensaje,id){
                swal({
                    title: pregunta,
                    text: mensaje,
                    type: "error",
                    showCancelButton: true,
                    confirmButtonColor: "#CA002D",
                    confirmButtonText: "<i class='fa fa-check'></i> ¡Si, eliminar!",
                    cancelButtonText: "<i class='fa fa-times'></i> Cancelar",
                    confirmButtonClass: 'btn btn-success',
                    cancelButtonClass: 'btn btn-danger',
                    buttonsStyling: true
                }).then(function() {
                     location.href = "${request.contextPath}/roleLG/remove/"+id;
                });
            }
        </script>
    </head>
    <body>
		<g:render template="/layouts/menu" />
		<!-- .menu-box -->
		<div class="breadcrumb-box">
		  <div class="container">
			<ul class="breadcrumb">
			  <li><a href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
			  <li class="active"><g:message code="default.list.label" args="[entitiesName]" /></li>
			</ul>
		  </div>
		</div>
		<!-- .breadcrumb-box -->
        <a href="#list-roleLG" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav_topbar" role="navigation">
            <ul>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
                <div class="col-xs-6 col-xs-offset-2" style="float:right;padding: 0px;">
					<g:if test="${roleLGCount != 0 || session.getAttribute('roleLG_search_word')}">
					<g:form action="index" method="POST" name="search_form">
						<div class="input-group">
							<div class="input-group-btn search-panel">
								<button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
									<span id="search_concept">${session.getAttribute('roleLG_search_rows')} Registros</span> <span class="caret"></span>
								</button>
								<ul class="dropdown-menu" role="menu">
								  <li><a href="#10">10 Registros</a></li>
								  <li><a href="#20">20 Registros</a></li>
								  <li><a href="#50">50 Registros</a></li>
								  <li><a href="#100">100 Registros</a></li>
								</ul>
							</div>
							<input type="hidden" name="search_rows" id="search_rows" value="${session.getAttribute('roleLG_search_rows')}">
							<input type="hidden" name="search_clean" id="search_clean" value="0">
							<input type="text" class="form-control" name="search_word" id="search_word" placeholder="Palabra a buscar..." value="${session.getAttribute('roleLG_search_word')}">
							<span class="input-group-btn">
								<button id="btn-search" class="btn btn-primary" type="button"><li class="fa fa-search fa-lg"></li></button>
							</span>
						</div>
					</g:form>
					</g:if>
				</div>
            </ul>
        </div>
        <div id="list-roleLG" class="content scaffold-list" role="main">
            <g:if test="${flash.message}">
				<script type="text/javascript">					  
					  $.amaran({
						'theme'     :'awesome ok',
						'delay'     :5000,
						'position'  :'top left',
						'content'   :{
							bgcolor:'#27ae60',
							color:'#fff',
							title:'¡Mensaje!',
							message:'${flash.message}',
							info:'', %{--<g:formatDate format="yyyy-MM-dd HH:mm:ss" date="${new Date()}"/>--}%
							icon:'fa fa-bell-o fa-2x'
						},
						'inEffect': 'slideLeft',
						'outEffect' :'slideLeft'
					});
				</script>
			</g:if>
            </br>
            <f:table collection="${roleLGList}" />
			
			<!--
			<table>
				<g:if test="${roleLGCount != 0}">
                <thead>
                    <tr>
                        <g:sortableColumn property="nombre" title="${message(code: 'roleLG.nombre.label', default: 'Name')}" />
                        <g:sortableColumn property="OTROCAMPO" title="OTRO CAMPO" />
                        <th style="width:100px" class="sortable"><a href="#"><g:message code="default.actions.label" default="Actions" /></a></th>
                    </tr>
                </thead>
				</g:if>
                <tbody>
                    <g:each in="${roleLGList}" var="item" status="i">
                        <tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
                            <td><g:link method="GET" resource="${item}">${item.nombre}</g:link></td>
                            <td>${item.OTROCAMPO}</td>
                            <td>
								<center>
									<a class="operations_icon red" onclick="jconfirm('${message(code: 'default.delete.ask.message', default: 'Are you sure?')}','${message(code: 'default.delete.info_personal.message', default: 'You are deleting the record.', args:[item.nombre])}','${item.id}');" title="¡Eliminar!"><li class="fa fa-trash"></li></a>
								</center>
							</td>
                        </tr>
                    </g:each>
                    <g:if test="${roleLGCount == 0}">
						<tr>
							<td colspan="3" style="text-align:center"></br></br><img src="${request.contextPath}/assets/empty/default.png" border="0px"/></br><span style="font-size:18px;color:#515151;"><g:message code="default.table.empty.label" args="[entitiesName.toLowerCase()]"/></span></br></br></td>
						</tr>
                    </g:if>
                </tbody>
            </table>
			-->
			
            <div class="pagination">
                <g:paginate total="${roleLGCount ?: 0}" />
            </div>
        </div>
    </body>
</html>

grails-app/views/roleLG/show.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'roleLG.label', default: 'RoleLG')}" />
        <g:set var="entitiesName" value="${message(code: 'roleLG.label', default: 'RoleLGs')}" />
        <title><g:message code="default.show.label" args="[entityName]" /></title>
        <script language="javascript">
			$( document ).ready(function() {
				$("#myTime").show();
			});
			
            function jconfirm(pregunta,mensaje){
                swal({
                    title: pregunta,
                    text: mensaje,
                    type: "error",
                    showCancelButton: true,
                    confirmButtonColor: "#CA002D",
                    confirmButtonText: "<i class='fa fa-check'></i> ¡Si, eliminar!",
                    cancelButtonText: "<i class='fa fa-times'></i> Cancelar",
                    confirmButtonClass: "btn btn-success",
                    cancelButtonClass: "btn btn-danger",
                    buttonsStyling: true
                }).then(function() {
                     $( "#delete_form" ).submit();
                });
            }
            
            function go(id_tag){
				$('[name="footer-'+id_tag+'"]')[0].click();
			}
        </script>
    </head>
    <body>
		<g:render template="/layouts/menu" />
		<!-- .menu-box -->
		<div class="breadcrumb-box">
		  <div class="container">
			<ul class="breadcrumb">
			  <li><a href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
			  <li><g:link action="index"><g:message code="default.list.label" args="[entitiesName]" /></g:link></li>
			  <li class="active"><g:message code="default.show.label" args="[entityName]" /></li>
			</ul>
		  </div>
		</div>
		<!-- .breadcrumb-box -->
        <a href="#show-roleLG" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav_topbar" role="navigation">
            <ul>
                <li><a href="javascript:go('edit')"		class="edit"><g:message code="default.button.edit.label" default="Edit" /></a></li>
                <li><a href="javascript:go('delete')"	class="delete"><g:message code="default.button.delete.label" default="Delete" /></a></li>
                <li><a href="javascript:go('close')"	class="close"><g:message code="default.button.close.label" default="close" /></a></li>
            </ul>
        </div>
        <div id="show-roleLG" class="content scaffold-show" role="main">
            <g:if test="${flash.message}">
				<script type="text/javascript">
				  <script type="text/javascript">					  
					  $.amaran({
						'theme'     :'awesome ok',
						'delay'     :5000,
						'position'  :'top left',
						'content'   :{
							bgcolor:'#27ae60',
							color:'#fff',
							title:'¡Mensaje!',
							message:'${flash.message}',
							info:'', %{--<g:formatDate format="yyyy-MM-dd HH:mm:ss" date="${new Date()}"/>--}%
							icon:'fa fa-bell-o fa-2x'
						},
						'inEffect': 'slideLeft',
						'outEffect' :'slideLeft'
					});
				</script>
			</g:if>
            
            <f:display bean="roleLG" />
            
            %{--
			<f:with bean="roleLG">
                <ol class="property-list roleLG">
                    <li class="fieldcontain">
                        <span id="nombre-label" class="property-label"><g:message code="roleLG.nombre.label" default="Nombre" /></span>
                        <div class="property-value" aria-labelledby="nombre-label"><f:display property="nombre"/></div>
                    </li>
                </ol>
            </f:with>
			--}%
            
            <g:form resource="${this.roleLG}" method="DELETE" name="delete_form">
				<fieldset class="buttons">
					<g:link name="footer-edit" class="edit" action="edit" resource="${this.roleLG}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
					<g:link name="footer-delete" class="delete" url="javascript:void(0)" onclick="jconfirm('${message(code: 'default.delete.ask.message', default: 'Are you sure?')}','${message(code: 'default.delete.info.message', default: 'You are deleting the record.')}');"><g:message code="default.button.delete.label" default="Delete" /></g:link>
                    <g:link name="footer-close" class="close" action="index"><g:message code="default.button.close.label" default="Close" /></g:link>
                </fieldset>
            </g:form>
        </div>
    </body>
</html>