grails-app/domain/ws/UserLGRoleLG.groovy
package ws

import grails.gorm.DetachedCriteria
import groovy.transform.ToString

import org.apache.commons.lang.builder.HashCodeBuilder

@ToString(cache=true, includeNames=true, includePackage=false)
class UserLGRoleLG implements Serializable {

	private static final long serialVersionUID = 1

	UserLG userLG
	RoleLG roleLG

	UserLGRoleLG(UserLG u, RoleLG r) {
		this()
		userLG = u
		roleLG = r
	}

	@Override
	boolean equals(other) {
		if (!(other instanceof UserLGRoleLG)) {
			return false
		}

		other.userLG?.id == userLG?.id && other.roleLG?.id == roleLG?.id
	}

	@Override
	int hashCode() {
		def builder = new HashCodeBuilder()
		if (userLG) builder.append(userLG.id)
		if (roleLG) builder.append(roleLG.id)
		builder.toHashCode()
	}

	static UserLGRoleLG get(long userLGId, long roleLGId) {
		criteriaFor(userLGId, roleLGId).get()
	}

	static boolean exists(long userLGId, long roleLGId) {
		criteriaFor(userLGId, roleLGId).count()
	}

	private static DetachedCriteria criteriaFor(long userLGId, long roleLGId) {
		UserLGRoleLG.where {
			userLG == UserLG.load(userLGId) &&
			roleLG == RoleLG.load(roleLGId)
		}
	}

	static UserLGRoleLG create(UserLG userLG, RoleLG roleLG, boolean flush = false) {
		def instance = new UserLGRoleLG(userLG: userLG, roleLG: roleLG)
		instance.save(flush: flush, insert: true)
		instance
	}

	static boolean remove(UserLG u, RoleLG r, boolean flush = false) {
		if (u == null || r == null) return false

		int rowCount = UserLGRoleLG.where { userLG == u && roleLG == r }.deleteAll()

		if (flush) { UserLGRoleLG.withSession { it.flush() } }

		rowCount
	}

	static void removeAll(UserLG u, boolean flush = false) {
		if (u == null) return

		UserLGRoleLG.where { userLG == u }.deleteAll()

		if (flush) { UserLGRoleLG.withSession { it.flush() } }
	}

	static void removeAll(RoleLG r, boolean flush = false) {
		if (r == null) return

		UserLGRoleLG.where { roleLG == r }.deleteAll()

		if (flush) { UserLGRoleLG.withSession { it.flush() } }
	}

	static constraints = {
		roleLG validator: { RoleLG r, UserLGRoleLG ur ->
			if (ur.userLG == null || ur.userLG.id == null) return
			boolean existing = false
			UserLGRoleLG.withNewSession {
				existing = UserLGRoleLG.exists(ur.userLG.id, r.id)
			}
			if (existing) {
				return 'userRole.exists'
			}
		}
	}

	static mapping = {
		id composite: ['userLG', 'roleLG']
		version false
	}
}

grails-app/controllers/ws/UserLGRoleLGController.groovy
package ws

import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
class UserLGRoleLGController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond UserLGRoleLG.list(params), model:[userLGRoleLGCount: UserLGRoleLG.count()]
    }

    def show(UserLGRoleLG userLGRoleLG) {
        respond userLGRoleLG
    }

    def create() {
        respond new UserLGRoleLG(params)
    }

    @Transactional
    def save(UserLGRoleLG userLGRoleLG) {
        if (userLGRoleLG == null) {
            transactionStatus.setRollbackOnly()
            notFound()
            return
        }

        if (userLGRoleLG.hasErrors()) {
            transactionStatus.setRollbackOnly()
            respond userLGRoleLG.errors, view:'create'
            return
        }

        userLGRoleLG.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'userLGRoleLG.label', default: 'UserLGRoleLG'), userLGRoleLG.id])
                redirect userLGRoleLG
            }
            '*' { respond userLGRoleLG, [status: CREATED] }
        }
    }

    def edit(UserLGRoleLG userLGRoleLG) {
        respond userLGRoleLG
    }

    @Transactional
    def update(UserLGRoleLG userLGRoleLG) {
        if (userLGRoleLG == null) {
            transactionStatus.setRollbackOnly()
            notFound()
            return
        }

        if (userLGRoleLG.hasErrors()) {
            transactionStatus.setRollbackOnly()
            respond userLGRoleLG.errors, view:'edit'
            return
        }

        userLGRoleLG.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'userLGRoleLG.label', default: 'UserLGRoleLG'), userLGRoleLG.id])
                redirect userLGRoleLG
            }
            '*'{ respond userLGRoleLG, [status: OK] }
        }
    }

    @Transactional
    def delete(UserLGRoleLG userLGRoleLG) {

        if (userLGRoleLG == null) {
            transactionStatus.setRollbackOnly()
            notFound()
            return
        }

        userLGRoleLG.delete flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'userLGRoleLG.label', default: 'UserLGRoleLG'), userLGRoleLG.id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'userLGRoleLG.label', default: 'UserLGRoleLG'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails-app/views/userLGRoleLG/create.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'userLGRoleLG.label', default: 'Usuario-Rol')}" />
        <g:set var="entitiesName" value="${message(code: 'userLGRoleLG.label', default: 'Usuarios-Roles')}" />
        <title><g:message code="default.create.label" args="[entityName]" /></title>
    </head>
    <body>
		<g:render template="/layouts/menu" />
        <a href="#create-userLGRoleLG" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entitiesName]" /></g:link></li>
            </ul>
        </div>
        <div id="create-userLGRoleLG" class="content scaffold-create" role="main">
            <h1><g:message code="default.create.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <g:hasErrors bean="${this.userLGRoleLG}">
            <ul class="errors" role="alert">
                <g:eachError bean="${this.userLGRoleLG}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                </g:eachError>
            </ul>
            </g:hasErrors>
            <g:form action="save">
                <fieldset class="form">
                    <f:all bean="userLGRoleLG"/>
                </fieldset>
                <fieldset class="buttons">
                    <g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>

grails-app/views/userLGRoleLG/edit.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'userLGRoleLG.label', default: 'Usuario-Rol')}" />
        <g:set var="entitiesName" value="${message(code: 'userLGRoleLG.label', default: 'Usuarios-Roles')}" />
        <title><g:message code="default.edit.label" args="[entityName]" /></title>
    </head>
    <body>
		<g:render template="/layouts/menu" />
        <a href="#edit-userLGRoleLG" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entitiesName]" /></g:link></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="edit-userLGRoleLG" class="content scaffold-edit" role="main">
            <h1><g:message code="default.edit.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <g:hasErrors bean="${this.userLGRoleLG}">
            <ul class="errors" role="alert">
                <g:eachError bean="${this.userLGRoleLG}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                </g:eachError>
            </ul>
            </g:hasErrors>
            <g:form resource="${this.userLGRoleLG}" method="PUT">
                <g:hiddenField name="version" value="${this.userLGRoleLG?.version}" />
                <fieldset class="form">
                    <f:all bean="userLGRoleLG"/>
                </fieldset>
                <fieldset class="buttons">
                    <input class="save" type="submit" value="${message(code: 'default.button.update.label', default: 'Update')}" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>

grails-app/views/userLGRoleLG/index.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'userLGRoleLG.label', default: 'Usuario-Rol')}" />
        <g:set var="entitiesName" value="${message(code: 'userLGRoleLG.label', default: 'Usuarios-Roles')}" />
        <title><g:message code="default.list.label" args="[entityName]" /></title>
    </head>
    <body>
		<g:render template="/layouts/menu" />
        <a href="#list-userLGRoleLG" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="list-userLGRoleLG" class="content scaffold-list" role="main">
            <h1><g:message code="default.list.label" args="[entitiesName]" /></h1>
            <g:if test="${flash.message}">
                <div class="message" role="status" style="float:left;width:97%">${flash.message}</div>
            </g:if>
            <!--
            <f:table collection="${userLGRoleLGList}" />
			-->
			
			<table>
                <thead>
                    <tr>
                        <g:sortableColumn property="userLG" title="${message(code: 'userLGroleLG.userLG.label', default: 'User')}" />
                        <g:sortableColumn property="roleLG" title="${message(code: 'userLGroleLG.roleLG.label', default: 'Role')}" />
                    </tr>
                </thead>

                <tbody>
                    <g:each in="${userLGRoleLGList}" var="userLGRoleLG" status="i">
                        <tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
                            <td><g:link method="GET" resource="${[userLGRoleLG.userLG,userLGRoleLG.roleLG.id]}">${userLGRoleLG.userLG.toString().replaceAll("UserLG\\(username:", "").replaceAll("\\)", "")}</g:link></td>
                            <td>${userLGRoleLG.roleLG.toString().replaceAll("RoleLG\\(authority:", "").replaceAll("\\)", "")}</td>
                        </tr>
                    </g:each>
                </tbody>
            </table>


            <div class="pagination">
                <g:paginate total="${userLGRoleLGCount ?: 0}" />
            </div>
        </div>
    </body>
</html>

grails-app/views/userLGRoleLG/show.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'userLGRoleLG.label', default: 'Usuario-Rol')}" />
        <g:set var="entitiesName" value="${message(code: 'userLGRoleLG.label', default: 'Usuarios-Roles')}" />
        <title><g:message code="default.show.label" args="[entityName]" /></title>
    </head>
    <body>
		<g:render template="/layouts/menu" />
        <a href="#show-userLGRoleLG" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entitiesName]" /></g:link></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="show-userLGRoleLG" class="content scaffold-show" role="main">
            <h1><g:message code="default.show.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <f:display bean="userLGRoleLG" />
            <g:form resource="${this.userLGRoleLG}" method="DELETE">
                <fieldset class="buttons">
                    <g:link class="edit" action="edit" resource="${this.userLGRoleLG}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
                    <input class="delete" type="submit" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>